Document Approval on RFC-674
lsst/LDM-732 pull request #2
Opened 2020-02-26 19:05 UTC by gcomoretto

2020-05-07 21:22 UTC, leannep requested changes
Main comment is that many test case objectives contain implementation details. These details should be in the test case procedure and the objective should provide a clear statement of the goal of the test case. I have provided suggestions for rephrasing - feel free to improve on them.

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +
This is not an objective but rather a description of how the test will be carried out.  The test objective should define the overall goal and achievement of the test execution. 

E.g  "Verify the integration of the summit to base network by demonstrating a sustained and uninterrupted transfer of  data between summit and base over 1 day period at or exceeding  rates specified in
  \citeds{LDM-142}."

The phases should be moved into either the test procedure or should be separate test cases that must be executed to verify this requirement

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +\textbf{Precondition:} \\
Objective reads more like a test case. Rephrase to something like: 
"Verify reliability of summit to base network by demonstrating reconnection and recovery to
transfer of data at or exceeding rates specified in \citeds{LDM-142} following a cut in network. 

Remaining details should be moved to the test case procedure.

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +5{[}second{]}, i.e. at or exceeding rates specified in \citeds{LDM-142}.
Simplify to:
Verify that the base to archive network is capable
of transferring images acquired for prompt processing at or exceeding rates specified in \citeds{LDM-142}, i.e in oArchiveMaxTransferTime = 5{[}second{]}."

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +
"Verify the availability of Summit to Base Network by demonstrating that the mean time between failures is less than summToBaseNetMTBF (90 days) over 1 year."

Move the details (Via monitoring and ~comparing with at least 6 months of historical data
on the link) into the test case procedure.

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +
"Verify Base to Archive Network Reliability by demonstrating that the network can recover from outages within baseToArchNetMTTR = 48{[}hour{]}."

Details about how the outage is simulated (i.e After disconnecting fiber at a location in the Base - Archive, network)  should be in the test case procedure.

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +
"Verify Base to Archive Network Secondary Link failover and capacity, and subsequent recovery primary. Demonstrate use of secondary path in ``catch-up'' mode."

Details of how, e.g by simulations to go to the test case procedure.

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +
Verify archiving of data to  Data Access Center Network at or exceeding rates specified in \citeds{LDM-142}, i.e at archToDacBandwidth = 10000{[}megabit per second{]},.

Montitoring/analysis details to go to the test case procedure

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +
Verify availability of archiving to Data Access Center Network using test and historical data of or exceedding archToDacNetMTBF= 180{[}day{]).

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +
Verify reliability of Archive to Data Access Center Network by demonstrating successful failover and capacity to the secondary part and  subsequent recovery to primary within or exceeding chToDacNetMTTR =
48{[}hour{]}.

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +
Verify Summit to Base Network Ownership and Operation by LSST and/or the operations entity by inspection of  operations contracts and Indefeasible Rights

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +capacity on secondary path.
Verify Archive to Data Access Center Network via Secondary Link by simulating a failure on primary path and capacity on the secondary path.

2020-05-07 21:22 UTC, leannep commented on ve_details.tex
> +
Verify the availability of the Base to Archive Network communications by demonstrating that it  meets or exceeds a mean time between failures, measured over a 1-yr period of   MTBF > baseToArchNetMTBF (180[day])

2022-05-08 20:46 UTC, merged

2022-05-08 20:48 UTC, womullan commented
This RFC was implemtented.. ages ago ...